# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'QSTechSample' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for QSTechSample
      
    pod 'EncryptedCoreData', :git => 'https://github.com/project-imas/encrypted-core-data.git'
    
    pod 'MBProgressHUD', :git =>
    'https://github.com/jdg/MBProgressHUD.git'
    
    
    target 'QSTechSampleTests' do
        inherit! :search_paths
        # Pods for testing
    end
    
end
